export const MR_MARKET_ROUTER_ABI = [
  'constructor(address initialReceiver)',
  'function owner() view returns (address)',
  'function receiver() view returns (address)',
  'function supportedTokens(address token) view returns (bool)',
  'function routeFunds(bytes32 requestId, address token, uint256 amount, bytes32 payloadHash)',
  'function requestWithdrawal(bytes32 requestId, address token, uint256 amount, address recipient, bytes32 payloadHash)',
  'function setReceiver(address newReceiver)',
  'function setSupportedToken(address token, bool supported)',
  'event FundsRouted(bytes32 indexed requestId, address indexed user, address indexed token, uint256 amount, bytes32 payloadHash, address receiver)',
  'event WithdrawalRequested(bytes32 indexed requestId, address indexed user, address indexed token, uint256 amount, address recipient, bytes32 payloadHash)',
  'event ReceiverUpdated(address oldReceiver, address newReceiver)',
  'event TokenSupportUpdated(address token, bool supported)',
  'error ZeroAddress()',
  'error ZeroAmount()',
  'error Unauthorized()',
  'error TokenUnsupported()',
  'error TokenTransferFailed()',
] as const;
