export const MR_MARKET_VAULT_ABI = [
  'constructor()',
  'function admin() view returns (address)',
  'function deposit(address token, uint256 amount)',
  'function userPayout(address user, address token, uint256 amount)',
  'function adminWithdraw(address token, uint256 amount)',
  'function adminSweep(address token, address to, uint256 amount)',
  'event Deposited(address indexed user, address indexed token, uint256 amount)',
  'event UserPayout(address indexed user, address indexed token, uint256 amount)',
  'event AdminWithdrawal(address indexed admin, address indexed token, uint256 amount)',
  'event AdminSweep(address indexed admin, address indexed token, address indexed to, uint256 amount)',
  'error ZeroAddress()',
  'error ZeroAmount()',
  'error Unauthorized()',
  'error TokenTransferFailed()',
] as const;
