/* eslint-disable @typescript-eslint/no-explicit-any */
import {
  Body,
  Controller,
  Delete,
  Get,
  Param,
  Post,
  UseGuards,
} from '@nestjs/common';
import { ApiOperation, ApiResponse, ApiTags } from '@nestjs/swagger';
import { JwtAuthGuard } from 'src/modules/auth/jwt-auth.guard';
import { ExchangeInitService } from 'src/modules/infrastructure/exchange-init/exchange-init.service';
import { ExchangeApiKeyService } from 'src/modules/market-making/exchange-api-key/exchange-api-key.service';

import { AddAPIKeyDto } from './exchanges.dto';

@ApiTags('Admin/Exchanges')
@Controller('admin/exchanges')
@UseGuards(JwtAuthGuard)
export class AdminExchangesController {
  constructor(
    private readonly exchangeService: ExchangeApiKeyService,
    private readonly exchangeInitService: ExchangeInitService,
  ) {}

  @Get('/keys')
  @ApiOperation({ summary: 'Get all API keys' })
  @ApiResponse({ status: 200, description: 'Return all API keys' })
  async getAllAPIKeys() {
    return await this.exchangeService.readAllAPIKeys();
  }

  @Post('/keys')
  @ApiOperation({ summary: 'Add a new API key' })
  @ApiResponse({ status: 200, description: 'API key added successfully' })
  async addAPIKey(@Body() data: AddAPIKeyDto) {
    const keyData = { ...data };

    // We cast to any here because key_id is generated by the database/entity
    const savedKey = await this.exchangeService.addApiKey(keyData as any);

    await this.exchangeInitService.refreshExchanges('api-key-added');

    return savedKey;
  }

  @Get('/key-pair')
  @ApiOperation({ summary: 'Get encryption public key' })
  @ApiResponse({ status: 200, description: 'Return encryption public key' })
  async getEncryptionPublicKey() {
    return this.exchangeService.getEncryptionPublicKey();
  }

  @Delete('/keys/:key_id')
  @ApiOperation({ summary: 'Remove an API key' })
  @ApiResponse({ status: 200, description: 'API key removed successfully' })
  async removeAPIKey(@Param('key_id') key_id: string) {
    await this.exchangeService.removeAPIKey(key_id);
    await this.exchangeInitService.refreshExchanges('api-key-removed');

    return { success: true };
  }

  @Post('/keys/:key_id/default')
  @ApiOperation({ summary: 'Set an API key as default for its exchange' })
  @ApiResponse({ status: 200, description: 'Default API key updated' })
  async setDefaultAPIKey(@Param('key_id') key_id: string) {
    const updatedKey = await this.exchangeService.setDefaultAPIKey(key_id);

    await this.exchangeInitService.refreshExchanges('api-key-default-updated');

    return updatedKey;
  }

  @Post('/reload')
  @ApiOperation({ summary: 'Reload initialized exchange instances' })
  @ApiResponse({ status: 200, description: 'Exchange instances reloaded' })
  async reloadExchanges() {
    await this.exchangeInitService.refreshExchanges('manual-reload');

    return { success: true };
  }
}
